apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  annotations:
    karpenter.sh/do-not-evict: "true"
  name: self-hosted-runner-deployment
  namespace: actions-runner-system
spec:
  template:
    spec:
      labels:
        - azure-linux
      organization: iree-org
      resources:
        requests:
          cpu: 45000m
          memory: 50000Mi
